# 项目相关配置
bit:
  # 名称
  name: bit
  # 版本
  version: 1.1.0
  # 版权年份
  copyrightYear: 2022
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/bit/uploadPath，Linux配置 /home/bit/uploadPath）
  profile: D:/bit/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: char
  # 验证码图片格式 GIF 和 png
  captchaImageFormat: gif
  # 验证码长宽
  captchaWidth: 160
  captchaHeight: 60

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 7080
  servlet:
    # 应用的访问路径
    context-path: /
    encoding:
      charset: UTF-8
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.bit: debug
    org.springframework: debug

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: dev
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  data:
    # redis 配置
    redis:
      # 地址
      host: dongxing.fun
      # 端口，默认为6379
      port: 9547
      # 数据库索引
      database: 0
      # 密码
      password:
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    # 主库数据源
    master:
      url: jdbc:mysql://dongxing.fun:9546/bit?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: root
      pool-name: HikariPool-master
    # 从库数据源
    slave:
      # 从数据源开关/默认关闭
      enabled: false
      url:
      username:
      password:
      pool-name: HikariPool-slave
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: F63190314D4CFD24CD1294F0003636B62EE76B1BE25230CEF5EBA83A77973945
  # 令牌有效期（默认30分钟）
  expireTime: 30

## MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.bit.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# springdoc Swagger配置
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha


# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*
